name: workflow

on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ~/GolandProjects/hello-api

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest 
    steps:
    
    - name: Build
      run: make build

    - name: Copy Files
      run: |
        mkdir  artifacts
        cp api artifacts/.

    - name: Archive #
      uses: actions/upload-artifact@v2
      with:
        name: api #
        path: artifacts
